server:
  servlet:
    context-path: /ZModule



spring:
  thymeleaf:
    cache: false
    encoding: utf-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username:
    password:
    url:
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
